"""Retrieval tuning constants shared by screening and extraction."""

from __future__ import annotations

from config.user_orchestrator import EMBEDDING_SETTINGS


# human readable hint: retrieval constants control how many full-text chunks are kept before LLM review.
RETRIEVAL_FALLBACK_TOP_K = 20
RETRIEVAL_WEAK_MIN_NON_TITLE = 3
RETRIEVAL_WEAK_MIN_WORDS = 280
RETRIEVAL_FRAGMENTED_MAX_SHARE = 0.40
RETRIEVAL_MIN_NON_TITLE_TARGET = 2
RETRIEVAL_MIN_METHOD_TARGET = 1
RETRIEVAL_DATA_PROMPT_BUDGET_RATIO = 0.60
RETRIEVAL_DATA_PROMPT_BUDGET_MIN_TOKENS = 12_000
RETRIEVAL_ASSUMED_CHUNK_TOKENS = 420
RETRIEVAL_MAX_NON_TITLE_CHUNKS = 24
RETRIEVAL_CHUNK_PROMPT_OVERHEAD_TOKENS = 28
RETRIEVAL_DIVERSITY_SECTION_SOFT_CAP = 2
RETRIEVAL_DIVERSITY_PAGE_WINDOW_SIZE = 2
RETRIEVAL_DIVERSITY_PAGE_WINDOW_SOFT_CAP = 2
RETRIEVAL_DIVERSITY_NEAR_DUPLICATE_JACCARD = 0.82
RETRIEVAL_COUNTEREVIDENCE_MAX_PAIRS = 2
RETRIEVAL_COUNTEREVIDENCE_MAX_SCORE = 0.08
RETRIEVAL_COUNTEREVIDENCE_MIN_NEG_SCORE = 0.02
RETRIEVAL_COUNTEREVIDENCE_PAGE_DISTANCE = 4
RETRIEVAL_COUNTEREVIDENCE_MIN_PRIMARY_SCORE = 0.02
RETRIEVAL_COUNTEREVIDENCE_MIN_NON_TITLE_CAP = 6
RETRIEVAL_PRECISION_MEDIUM_NON_TITLE_CAP = 4
RETRIEVAL_MONITORING_ONLY_PENALTY = 0.10
FULLTEXT_SENTENCE_TARGET = int(EMBEDDING_SETTINGS.get("chunk_size", 20) or 20)
RETRIEVAL_MIN_SENTENCE_FLOOR = max(6, int(FULLTEXT_SENTENCE_TARGET * 0.6))
